version: 2.1
commands:
  print_pipeline_id:
    description: "This is a test command that prints Circle CI Workflow ID"
    steps:
      # Circle CI Workflow ID Environment Variable
      - run: echo ${CIRCLE_WORKFLOW_ID}
jobs:
  my-command:
    docker:
      - image: cimg/base:stable
    steps:
      - print_pipeline_id
  
workflows:
  welcome:
    jobs:
      - my-command